name: Build EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install pygame pyinstaller

      - name: Build EXE
        run: pyinstaller --onefile --noconfirm Spane.py

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: Spane-exe
          path: dist/*.exe
